config/routes.rb
DynamicModels::Application.routes.draw do

  get "static/risk_report"
  get "static/efficiency"

  resources :models, except: [:edit, :update]

  get 'proxies/:table_name', to: 'proxies#index', as: 'proxies'
  get 'proxies/:table_name/new', to: 'proxies#new', as: 'new_proxy'
  get 'proxies/:table_name/:id', to: 'proxies#show', as: 'proxy'
  get 'proxies/:table_name/:id/edit', to: 'proxies#edit', as: 'edit_proxy'
  post 'proxies/:table_name', to: 'proxies#create'
  post 'proxies/:table_name/update_column', to: 'proxies#update_column', as: 'update_column_proxies'
  put 'proxies/:table_name/:id', to: 'proxies#update'
  patch 'proxies/:table_name/:id', to: 'proxies#update'
  delete 'proxies/:table_name/:id', to: 'proxies#destroy'

  # You can have the root of your site routed with "root"
  root 'models#index'

end

app/models/proxy.rb
class Proxy < ActiveRecord::Base

  HIDE_COLUMNS = %w[id created_at updated_at]

  class << self

    def visible_columns
      columns.reject do |column|
        HIDE_COLUMNS.include? column.name
      end.inject({}) do |h, column|
        h[column.name.to_sym] = column.type
        h
      end
    end

    def visible_column_names
      visible_columns.keys.map(&:to_s)
    end

  end
end

app/controllers/proxies_controller.rb
class ProxiesController < ApplicationController
  before_action :set_table
  before_action :set_proxy, only: [:show, :edit, :update, :destroy]

  # GET /proxies
  # GET /proxies.json
  def index
    @proxies = Proxy.order(:id)
    logger.debug "ProxiesController@#{__LINE__}#index #{@proxies.count}" if logger.debug?
  end

  # GET /proxies/1
  # GET /proxies/1.json
  def show
  end

  # GET /proxies/new
  def new
    @proxy = Proxy.new
  end

  # GET /proxies/1/edit
  def edit
  end

  # POST /proxies
  # POST /proxies.json
  def create
    @proxy = Proxy.new(proxy_params)

    respond_to do |format|
      if @proxy.save
        format.html { redirect_to proxy_url(@proxy, table_name: @table_name),
                      notice: t('proxies.was_created', name: @table_name.classify) }
        format.json { render action: 'show', status: :created, location: @proxy }
      else
        format.html { render action: 'new' }
        format.json { render json: @proxy.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /proxies/1
  # PATCH/PUT /proxies/1.json
  def update
    respond_to do |format|
      if @proxy.update(proxy_params)
        format.html { redirect_to proxy_url(@proxy, table_name: @table_name),
                      notice: t('proxies.was_updated', name: @table_name.classify) }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @proxy.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /proxies/1
  # DELETE /proxies/1.json
  def destroy
    @proxy.destroy
    respond_to do |format|
      format.html { redirect_to proxies_url,
                    notice: t('proxies.was_deleted', name: @table_name.classify) }
      format.json { head :no_content }
      format.js
    end
  end

  # POST /proxies/update_column
  # POST /proxies/update_column.js
  def update_column
    Proxy.transaction do
      if params[:force].present?
        changed = []
      else
        changed = Proxy.where('updated_at > ?', params[:taken]).pluck(:id)
        logger.debug "ProxiesController@#{__LINE__}#update_column #{changed.inspect}" if logger.debug?
      end
      if changed.empty?
        attribute = params[:attribute]
        values = params[attribute] || {}
        Proxy.where(id: values.keys).find_each do |proxy|
          value = values[proxy.id.to_s]
          proxy.update_attribute(attribute, value) if proxy.send(attribute) != value
        end
      end
      respond_to do |format|
        format.html { redirect_to proxies_url,
                      notice: changed.present? ? nil :
                                t('proxies.were_updated',
                                  name: @table_name.classify,
                                  attribute: attribute) }
        format.json { head :no_content }
        format.js {render text: changed.to_json}
      end
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_proxy
    @proxy = Proxy.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def proxy_params
    params[:proxy].permit!
  end

  def set_table
    @table_name = Proxy.table_name = params[:table_name]
    logger.debug "ProxiesController@#{__LINE__}#set_table #{ActiveRecord::Base.connection.tables.inspect}" if logger.debug?
    raise ActiveRecord::RecordNotFound unless Proxy.connection.tables.include? @table_name
  end
end

app/views/proxies/_form.html.haml
= simple_form_for@proxy,
  url: @proxy.new_record? ? proxies_path(table_name: @table_name) : proxy_path(@proxy, table_name: @table_name) do |f|
  - if @proxy.errors.any?
    #error_explanation
      %h2= "#{pluralize(@proxy.errors.count, "error")} prohibited this proxy from being saved:"
      %ul
        - @proxy.errors.full_messages.each do |msg|
          %li= msg
  .form-inputs
    - Proxy.visible_column_names.each do |column|
      = f.input column, label: column.titleize

  .actions
    = f.submit 'Save'

app/views/proxies/edit.html.haml
- title t('.title', name: @table_name.classify)

= render 'form'

= link_to t('show'), proxy_url(@proxy, table_name: @table_name)
\|
= link_to t('back'), proxies_path(table_name: @table_name)

app/views/proxies/index.html.haml
- title t('.title', name: @table_name.classify)

= form_tag update_column_proxies_path(table_name: @table_name) do
  = hidden_field_tag 'taken', Time.current.to_s(:milliseconds)
  = hidden_field_tag 'attribute'
  = hidden_field_tag 'force'
  %table
    %tr
      - Proxy.visible_column_names.each do |column|
        %th{column_name: column}
          = column.titleize
      %th
        = link_to t('cancel'), '#', style: 'display: none;',
          class: 'columns_control save_columns cancel', style: 'display: none;'
      %th
        = submit_tag t('.save_columns', default: 'Save'),
          style: 'display: none;',
          class: 'columns_control first_save save_columns'
        = submit_tag t('.force_save_columns', default: 'Overwrite'),
          style: 'display: none;',
          class: 'columns_control force_save_columns'
      %th

    - @proxies.each do |proxy|
      %tr
        - Proxy.visible_column_names.each do |column|
          %td= proxy.send column
        %td
          = link_to t('show'), proxy_path(proxy, table_name: @table_name), class: 'show'
        %td
          = link_to t('edit'), edit_proxy_path(proxy, table_name: @table_name),
            class: 'edit'
        %td
          = link_to t('destroy'), proxy_path(proxy, table_name: @table_name),
            :method => :delete, :data => { :confirm => t('are_you_sure') },
            class: 'destroy', remote: true

%br

= link_to t('.new_proxy'), new_proxy_path(table_name: @table_name), class: 'new'
= link_to t('.models'), models_path, class: 'index'

app/views/proxies/new.html.haml
- title t('.title', name: @table_name.classify)

= render 'form'

= link_to t('back'), proxies_path(table_name: @table_name)

app/views/proxies/show.html.haml
- title t('.title', name: @table_name.classify)

%dl
  - Proxy.visible_column_names.each do |column|
    %dt= column.titleize
    %dd= @proxy.send column

= link_to t('edit'), edit_proxy_path(@proxy, table_name: @table_name)
\|
= link_to t('back'), proxies_path(table_name: @table_name)