config/routes.rb
DynamicModels::Application.routes.draw do

  get "static/risk_report"
  get "static/efficiency"

  resources :models, except: [:edit, :update]

  get 'proxies/:table_name', to: 'proxies#index', as: 'proxies'
  get 'proxies/:table_name/new', to: 'proxies#new', as: 'new_proxy'
  get 'proxies/:table_name/:id', to: 'proxies#show', as: 'proxy'
  get 'proxies/:table_name/:id/edit', to: 'proxies#edit', as: 'edit_proxy'
  post 'proxies/:table_name', to: 'proxies#create'
  post 'proxies/:table_name/update_column', to: 'proxies#update_column', as: 'update_column_proxies'
  put 'proxies/:table_name/:id', to: 'proxies#update'
  patch 'proxies/:table_name/:id', to: 'proxies#update'
  delete 'proxies/:table_name/:id', to: 'proxies#destroy'

  # You can have the root of your site routed with "root"
  root 'models#index'

end

app/models/proxy.rb
class Proxy < ActiveRecord::Base

  HIDE_COLUMNS = %w[id created_at updated_at]

  class << self

    def visible_columns
      columns.reject do |column|
        HIDE_COLUMNS.include? column.name
      end.inject({}) do |h, column|
        h[column.name.to_sym] = column.type
        h
      end
    end

    def visible_column_names
      visible_columns.keys.map(&:to_s)
    end

  end
end

app/controllers/models_controller.rb
class ModelsController < ApplicationController

  before_action :set_table_name, only: [:show, :destroy]

  def index
    @table_names = Proxy.connection.tables.sort -
        %w[schema_migrations]
  end

  def show
    Proxy.table_name = @table_name
    @columns = Proxy.visible_columns
  end

  def new
  end

  def create
    content = YAML.parse(params[:file].read).to_ruby rescue nil
    logger.debug "ModelsController@#{__LINE__}#create #{content.class} #{Hash === content} #{content.inspect}" if logger.debug?
    return parse_error('not_hash') unless Hash === content
    return parse_error('not_single') if content.size > 1
    class_name = I18n.transliterate(content.keys.first, '_').classify
    table_name = class_name.tableize
    return parse_error('exists') if Proxy.connection.tables.include? table_name
    content = content.values.first
    return parse_error('not_hash') unless Hash === content
    return parse_error('empty') if content.size < 1
    Proxy.table_name = table_name
    ActiveRecord::Base.transaction do
      Proxy.connection.create_table table_name
      ok = true
      columns = []
      content.each do |column_name, type|
        begin
          Proxy.connection.add_column table_name, column_name, type
          columns << column_name
        rescue => e
          logger.info "ModelsController@#{__LINE__}#create #{table_name} #{column_name} #{type} #{e.message}"
          flash.alert = t(".wrong_field", column_name: column_name, type: type)
          ok = false
          render 'new'
          raise ActiveRecord::Rollback
        end
      end
      Proxy.connection.add_column table_name, :created_at, :datetime unless columns.include? 'created_at'
      Proxy.connection.add_column table_name, :updated_at, :datetime unless columns.include? 'updated_at'
      redirect_to models_url, notice: t('models.was_created', name: class_name) if ok
    end
#     render text: "#{class_name} #{table_name} #{content.inspect}"
  end

  def destroy
    Proxy.connection.drop_table @table_name
    redirect_to models_url, notice: t('models.was_deleted', name: @table_name.classify)
  end

  private

  def set_table_name
    @table_name = params[:id]
  end

  def parse_error(msg)
    logger.debug "ModelsController@#{__LINE__}#parse_error #{msg} #{params.inspect}" if logger.debug?
    flash.alert = t(".#{msg}")
    render 'new'
  end
end

app/views/models/index.html.haml
- title t('.title')

%table
  %tr
    %th
      = t('activerecord.attributes.model.name')
    %th
    %th
    %th

  - @table_names.each do |table_name|
    %tr
      %td= table_name.classify
      %td= link_to t('show'), model_path(table_name)
      %td
        = link_to t('destroy'), model_path(table_name), :method => :delete,
          :data => { :confirm => t('are_you_sure') }
      %td= link_to t('.browse'), proxies_path(table_name: table_name)

%br

= link_to t('.new_model'), new_model_path, class: 'new'
= link_to t('.risk_report'), static_risk_report_path, class: 'index'

app/views/models/new.html.haml
- title t('.title')

= form_tag models_path, multipart: true do
  = label_tag "file", t(".file")
  = file_field_tag "file"
  = submit_tag t('.upload')

%p.nav= link_to t('back'), models_path, :class => 'index'

app/views/models/show.html.haml
- title t('.title', name: @table_name.classify)

%dl
  - @columns.each do |name, type|
    %dt= name
    %dd= type

%p.nav= link_to t('back'), models_path, :class => 'index'